### ISSUE TITLE
Integration with vega-transform

### ISSUE THREAD

**Issue by akansal1** [vega/dataflow-api#1]
I want to use, vega-transform for declarative data manipulation in my web-app, for which, this seems to be a right alternative. On looking at code further, it looks as if you are not utilizing vega-transform in this packages.

I would like to know if, you have any plan to make that change in near future, or is there a way to integrate vega-transform in a product without utilizing charting capabilities of vega. I want to use it to implement, method chaining

May be I have understood it wrong, a small pointer towards a minimal architecture diagram can help me

Thanks!

**Comment by jheer** [comment]
I'm not sure what you mean. This project is a direct extension of vega-dataflow and vega-transforms, using many (though not all) of the transforms available in Vega. Are there specific transforms you'd like to apply that are missing? Or is there a specific syntax you wanted to use?

**Comment by akansal1** [comment]
Currently, I am using datalib for most of data manipulation, and d3 for [Multi-level nesting](http://learnjsdata.com/group_data.html). Given, no further development in datalib:

- I am looking to use vega-transform for all my data manipulation work.
- I am also looking for something that allow method chaining, to enable multi-step/sequential data manipulation

Example of Nested multi-level grouping and multi-aggregation:
**Input**
```javascript
[
  {"id": "A", "job": "Doctor", "region": "East","value":1},
  {"id": "B", "job": "Doctor", "region": "East","value":1},
  {"id": "C", "job": "Lawyer", "region": "East","value":1},
  {"id": "D", "job": "Lawyer", "region": "East","value":1},
  {"id": "E", "job": "Doctor", "region": "West","value":1},
  {"id": "F", "job": "Doctor", "region": "West","value":1},
  {"id": "G", "job": "Lawyer", "region": "West","value":1},
  {"id": "H", "job": "Lawyer", "region": "West","value":1}
]
```

**Possible Operation**
```javascript
{grouping_keys:['job','region'],
value_keys:['value'],
operations:['sum','mean']}
```

**Expected Output Structure** (Can be structured differently as well)
```javascript
{'Doctor':{'east':{'sum':2,'mean':1},'west':{sum:2,mean:1}}},
{'Lawyer':{'east':{'sum':2,'mean':1},'west':{sum:2,mean:1}}}
```
**OR**

```javascript
{key: "Doctor", values: [
   {key: "east", values: [
          {job:"Doctor",region:"east",sum:2,mean:1}]
     key: "west", values: [
          {job:"Doctor",region:"west",sum:2,mean:1}]
      ...]}
```

Thanks

**Comment by akansal1** [comment]
@jheer do you have any update on query ? 

thanks!

**Comment by jheer** [comment]
dataflow-api currently does not provide support for the multi-level nesting you describe above. You can achieve a flat aggregation result, however:

```javascript
var flow = df.dataflow([
  df.aggregate()
    .groupby(['job', 'region'])
    .measure([df.sum('value').as('sum'), df.mean('value').as('mean')])
]);
```

In the future, we could potentially extend dataflow-api to include hierarchy transforms ([`stratify`](https://vega.github.io/vega/docs/transforms/stratify/) and [`nest`](https://vega.github.io/vega/docs/transforms/nest/)) to generate nested tree structures as well.

**Comment by akansal1** [comment]
thanks
